# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: PhotoConsequences

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Create the app package
      run: dotnet publish -c Release -p:Platform="x64" -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true
    
    - name: View build directory
      run: tree .\PhotoConsequences\
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: VSTImageWinX64
        path: .\VSTImage\VSTImage\bin\x64\Release\net5.0-windows\win-x64\publish
